import { _decorator, easing } from 'cc';

export const easeFunctions: Array<(k: number) => number> = [
    easing.linear,
    easing.quadIn,
    easing.quadOut,
    easing.quadInOut,
    easing.cubicIn,
    easing.cubicOut,
    easing.cubicInOut,
    easing.quartIn,
    easing.quartOut,
    easing.quartInOut,
    easing.quintIn,
    easing.quintOut,
    easing.quintInOut,
    easing.sineIn,
    easing.sineOut,
    easing.sineInOut,
    easing.expoIn,
    easing.expoOut,
    easing.expoInOut,
    easing.circIn,
    easing.circOut,
    easing.circInOut,
    easing.elasticIn,
    easing.elasticOut,
    easing.elasticInOut,
    easing.backIn,
    easing.backOut,
    easing.backInOut,
    easing.bounceIn,
    easing.bounceOut,
    easing.bounceInOut,
    easing.smooth,
    easing.fade,
    easing.quadOutIn,
    easing.cubicOutIn,
    easing.quartOutIn,
    easing.quintOutIn,
    easing.sineOutIn,
    easing.expoOutIn,
    easing.circOutIn,
    easing.elasticOutIn,
    easing.backOutIn,
    easing.bounceOutIn,
    // 继续添加其他函数...
];

export enum EaseType {
    Linear = 0,
    QuadIn = 1,
    QuadOut = 2,
    QuadInOut = 3,
    CubicIn = 4,
    CubicOut = 5,
    CubicInOut = 6,
    QuartIn = 7,
    QuartOut = 8,
    QuartInOut = 9,
    QuintIn = 10,
    QuintOut = 11,
    QuintInOut = 12,
    SineIn = 13,
    SineOut = 14,
    SineInOut = 15,
    ExpoIn = 16,
    ExpoOut = 17,
    ExpoInOut = 18,
    CircIn = 19,
    CircOut = 20,
    CircInOut = 21,
    ElasticIn = 22,
    ElasticOut = 23,
    ElasticInOut = 24,
    BackIn = 25,
    BackOut = 26,
    BackInOut = 27,
    BounceIn = 28,
    BounceOut = 29,
    BounceInOut = 30,
    Smooth = 31,
    Fade = 32,
    QuadOutIn = 33,
    CubicOutIn = 34,
    QuartOutIn = 35,
    QuintOutIn = 36,
    SineOutIn = 37,
    ExpoOutIn = 38,
    CircOutIn = 39,
    ElasticOutIn = 40,
    BackOutIn = 41,
    BounceOutIn = 42,
}


